replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/webhook-app/webhook-app-backend
  tag: '4.0.0'
  pullPolicy: Always
env:
  SECRET_KEY: "change-me"
  DATABASE_PATH: "/data/events.db"
service:
  type: ClusterIP
  port: 5000
route:
  enabled: true
  host: ""
pvc:
  size: 1Gi
  storageClass: "gp3-csi"
